config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users

  # devise_scope :user do
  #   authenticated :user do
  #     root :to => 'posts#index'
  #   end
  #   unauthenticated :user do
  #     root :to => 'devise/registrations#new', as: :unauthenticated_root
  #   end
  # end

  resources :users
  resources :posts do
    resources :comments
  end

  root :to => 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  validates_presence_of :title, :body

  scope :order_by_latest, -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name
  has_many :posts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    comment_service = CommentService.new(@post.id, comments_params.merge!(user_id: current_user.id))
    comment = comment_service.call
    if comment.valid?
      redirect_to @post
    else
      render @post
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comments_params
    params.required(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = PostDecorator.decorate_collection(Post.eager_load(:user).order_by_latest)
  end

  def show
    @post = PostDecorator.decorate(@post)
  end

  def new
    @post = Post.new
  end

  def create
    @post = PostService.new(post_params, current_user.id).call
    if @post.valid?
      @post = PostDecorator.decorate(@post)
      render 'show'
    else
      render 'new'
    end
  end

  def update
    if @post.update(post_params)
      @post = PostDecorator.decorate(@post)
      render 'show'
    else
      render 'new'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

  def set_post
    @post = Post.includes(:comments).find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div class="media">
    <a class="pull-left" href="#">
        <img class="media-object" src="http://placehold.it/64x64" alt="">
    </a>
    <div class="media-body">
        <h4 class="media-heading"><%= comment.author.full_name %>
            <small><%= comment.created_at.strftime("%b %e, %Y %I:%M %p") %></small>
        </h4>
        <%= comment.body %>
    </div>
</div>

app/views/comments/_new.html.erb
<div class="well">
    <h4>Leave a Comment:</h4>
    <%= form_for([ @post, Comment.new], remote: true) do |form| %>
      <%= form.text_area :body, size: '100x5' %><br>
      <button type="submit" class="btn btn-primary">Submit</button>
    <% end %>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Message Board Test" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Message Board Test" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body, :as => :text, :input_html => {:rows => 10} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!-- Page Content -->
<div class="container">
    <div class="row">

        <!-- Blog Post Content Column -->
        <div class="col-lg-12" id="posts_container">
          <% @posts.each do |post| %>
            <div class="post_element">
                <h2><%= post.title %></h2>
                <p class="lead">
                    by <a href="#"><%= post.author.full_name %></a>
                </p>
                <hr>
                <p><span class="glyphicon glyphicon-time"></span> Posted on <%= post.created_at.strftime("%b %e, %Y %I:%M %p") %></p>
                <p class="lead">
                  <%= post.body %>
                </p>
                <hr>
                <button class="btn btn-success">
                 <%=link_to 'Read More', post_path(post) %>
                </button>
                <% if post.comments.any? %>
                    <span>Num Comments: <%= post.comments.length %></span>
                <% end %>
            </div>

            <% end %>
        </div>

    </div>
    <!-- /.row -->

<hr>

<% if current_user %>
  <%= link_to 'Create a new Post', new_post_path, class: 'btn btn-primary' %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<!-- Page Content -->
<div class="container">

  <div class="row">

        <!-- Title -->
        <h1><%= @post.title %></h1>

        <!-- Author -->
        <p class="lead">
            by <a href="#"><%= @post.author.full_name %></a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p><span class="glyphicon glyphicon-time"></span> Posted on <%= @post.created_at.strftime("%b %e, %Y %I:%M %p") %></p>

        <hr>

        <!-- Post Content -->
        <p class="lead"><%= @post.body %></p>

        <hr>

        <!-- Blog Comments -->

        <!-- Comments Form -->
        <%= render 'comments/new', post: @post %>

        <hr>

        <!-- Posted Comments -->
        <%= render @post.comments %>

  </div>
</div>

<%= link_to 'All Posts', posts_path %>

app/views/users/_user.html.erb
<td><%= link_to user.first_name + ' ' + user.last_name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>First name: <%= @user.first_name %></p>
<p>Last name: <%= @user.last_name %></p>
<p>Description: <%= @user.description if @user.description %></p>
<p>Email: <%= @user.email if @user.email %></p>